trigger:
- main

stages:
- stage: Build
  displayName: "Terraform Build Stage"
  pool:
    name: Terraform_automation_Pool

  jobs:
  - job: TerraformBuild
    displayName: "Terraform Plan Job"
    steps:
    - checkout: self

    - task: TerraformTask@5
      displayName: "TF Init"
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)/infra/terraform'
        backendServiceArm: 'Azure subscription 1(b4212e49-0fe7-42ae-b910-c899fd642e41)'
        backendAzureRmResourceGroupName: 'shwatank001-rg'
        backendAzureRmStorageAccountName: 'backendshwatank'
        backendAzureRmContainerName: 'backend-prod'
        backendAzureRmKey: 'dev.tfstate'

    - task: TerraformTask@5
      displayName: "TF Validate"
      inputs:
        provider: 'azurerm'
        command: 'validate'
        workingDirectory: '$(System.DefaultWorkingDirectory)/infra/terraform'

    - task: TerraformTask@5
      displayName: "TF Format"
      inputs:
        provider: 'azurerm'
        command: 'fmt'
        workingDirectory: '$(System.DefaultWorkingDirectory)/infra/terraform'

    - task: TerraformTask@5
      displayName: "TF Plan"
      inputs:
        provider: 'azurerm'
        command: 'plan'
        workingDirectory: '$(System.DefaultWorkingDirectory)/infra/terraform'
        environmentServiceNameAzureRM: 'Azure subscription 1(b4212e49-0fe7-42ae-b910-c899fd642e41)'

    - task: ArchiveFiles@2
      displayName: "Archive files"
      inputs:
        rootFolderOrFile: '$(Build.BinariesDirectory)'
        includeRootFolder: true
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
        replaceExistingArchive: true

    - task: PublishBuildArtifacts@1
      displayName: "Publish Build Artifacts"
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: '$(Build.BuildID)-TFbuild'
        publishLocation: 'Container'
